name: autonomous-loop
version: 1.0.0
description: |
  Automatically chains sessions when a session ends but work is incomplete.
  Uses 'autonomous' trigger from config or explicit variable.

# Only trigger if autonomous mode is enabled and we are not explicitly stopping
triggers:
  on_session_end:
    - if: "variables.get('autonomous_mode') == True and variables.get('stop_reason') != 'completed'"

actions:
  on_session_end:
    # 1. Extract context from the ending session
    - action: extract_handoff_context
      store_as: handoff_ctx

    # 2. Start new session with that context
    - action: start_new_session
      args: ["--print-transcript"] # Example argument
      prompt: |
        RESUMING SESSION (Autonomous Handoff)

        Previous Goal: {{ variables.handoff_ctx.initial_goal }}

        Last Status:
        {{ variables.handoff_ctx.git_status }}

        Please continue working on this task.

      # Only run if we actually got context
      when: "variables.get('handoff_ctx') is not None"
