name: session-lifecycle
description: "Core session lifecycle - title synthesis on first prompt"
type: lifecycle
version: "1.0"

settings:
  priority: 1  # High priority - runs early

triggers:
  on_prompt_submit:
    - action: synthesize_title
      when: "session.title == None"
