name: session-handoff
description: "Session summary generation and context handoff between sessions"
type: lifecycle

triggers:
  on_before_agent:
    - action: generate_handoff
      when: "event.data.get('prompt', '').strip().lower() in ['/clear', '/exit']"
      include:
        - artifacts
        - pending_tasks

  on_session_start:
    - action: inject_context
      when: "event.data.get('source') == 'clear'"
      source: previous_session_summary
      template: |
        ## Previous Session Context
        {{ summary }}
