name: session-handoff
description: "Session summary generation and context handoff between sessions"
type: lifecycle  # No phases, responds to events

triggers:
  on_session_start:
    # 1. Logic from _handle_event_session_start: Check for parent session on /clear or restart
    - action: find_parent_session
      when: "trigger_source == 'clear'"
      filter:
        status: handoff_ready
        same_project: true
        same_machine: true
        
    # 2. Restore context if parent found
    - action: restore_context
      source: parent_session_summary
      when: parent_session_found
      inject_as: system_context
      
    # 3. Mark parent as expired
    - action: mark_session_status
      target: parent
      status: expired
      when: context_restored

    # 4. Inject active task context (currently done in code, capturing here for completeness)
    - action: inject_context
      source: active_task
      when: has_active_task

  on_session_end:
    # Logic from _handle_event_session_end
    - action: generate_summary
      generator: llm
      template: default
      
    - action: mark_session_status
      status: handoff_ready

  on_prompt_submit:
    # Logic from _handle_event_before_agent
    
    # 1. Auto-title synthesis
    - action: synthesize_title
      when: "session.title == null"
      generator: llm

    # 2. Mark active (unless special command)
    - action: mark_session_status
      status: active
      when: "not prompt.strip().lower() in ['/clear', '/exit']"

    # 3. Handle /clear as early handoff
    - action: generate_summary
      when: "prompt.strip().lower() == '/clear'"
      generator: llm
