name: memory-sync
description: Synchronize memories and skills with filesystem for Git persistence
version: 1.0.0

triggers:
  on_session_start:
    - action: memory.sync_import
      
  on_session_end:
    - action: memory.sync_export
