name: memory-lifecycle
description: Standard memory lifecycle hooks
version: "1.0"
type: lifecycle
author: Gobby
settings:
  priority: 50 # Run before handoff (which might clear context?)

triggers:
  on_session_start:
    # Uses config defaults: importance_threshold=0.3, injection_limit=10
    - action: memory_inject

  on_before_agent:
    # Inject memories relevant to the user's prompt via semantic search
    - action: memory_recall_relevant
      limit: 5
      min_importance: 0.3

  on_session_end:
    - action: memory_extract
    - action: skills_learn
