# Agent TDD Workflow
# This workflow is designed for agents spawned to implement specific features.
# It enforces test-driven development: write tests first, then implement.
#
# Usage: Spawn an agent with this workflow:
#   call_tool(server_name="gobby-agents", tool_name="start_agent", arguments={
#       "prompt": "Implement user authentication",
#       "workflow": "agent-tdd",
#       "parent_session_id": "sess-parent",
#       "mode": "terminal",
#   })

name: agent-tdd
description: Test-driven development workflow for agents
version: "1.0"
type: step

variables:
  test_command: "uv run pytest -v"
  require_passing_tests: true
  min_test_count: 1

steps:
  - name: understand
    description: Understand the task requirements
    allowed_tools:
      - Read
      - Glob
      - Grep
      - WebSearch
      - WebFetch
      - TodoWrite
    blocked_tools:
      - Edit
      - Write
      - Bash

    on_enter:
      - action: inject_context
        template: |
          ## Understanding Phase (TDD Step 1)

          Before writing any code, thoroughly understand:
          1. What exactly needs to be implemented
          2. What the acceptance criteria are
          3. How it fits with existing code
          4. What edge cases to consider

          Research the codebase and existing patterns.
          DO NOT write any code yet.

    exit_conditions:
      - type: artifact_exists
        name: requirements_understood
        prompt: "Have you fully understood the requirements?"

    transitions:
      - to: write_tests
        when: artifact_exists("requirements_understood")

  - name: write_tests
    description: Write failing tests first
    allowed_tools:
      - Read
      - Glob
      - Grep
      - Edit
      - Write
      - Bash  # For running tests
      - TodoWrite
    blocked_tools: []

    on_enter:
      - action: inject_context
        template: |
          ## Test Writing Phase (TDD Step 2)

          Write tests FIRST, before implementation:
          1. Create test file(s) for the feature
          2. Write tests that define the expected behavior
          3. Run tests to confirm they fail:
             ```bash
             {{ test_command }}
             ```
          4. Tests should fail because implementation doesn't exist yet

          Remember: Red -> Green -> Refactor

    rules:
      - name: require_test_files
        when: "editing_non_test_file() and not tests_exist()"
        action: block
        message: "Write tests before implementation. Create test files first."

    exit_conditions:
      - type: artifact_exists
        name: tests_written

    transitions:
      - to: implement
        when: artifact_exists("tests_written")

  - name: implement
    description: Implement to make tests pass
    allowed_tools: all
    blocked_tools: []

    on_enter:
      - action: inject_context
        template: |
          ## Implementation Phase (TDD Step 3)

          Now implement the minimum code to make tests pass:
          1. Write the simplest implementation
          2. Run tests frequently:
             ```bash
             {{ test_command }}
             ```
          3. Stop as soon as tests pass
          4. Don't add extra features not covered by tests

    rules:
      - name: run_tests_frequently
        when: "edits_since_test_run() > 3"
        action: warn
        message: "Remember to run tests frequently"

    exit_conditions:
      - type: artifact_exists
        name: tests_passing

    transitions:
      - to: refactor
        when: artifact_exists("tests_passing")

  - name: refactor
    description: Refactor while keeping tests green
    allowed_tools: all
    blocked_tools: []

    on_enter:
      - action: inject_context
        template: |
          ## Refactor Phase (TDD Step 4)

          Now improve the code quality:
          1. Remove duplication
          2. Improve naming and structure
          3. Run tests after each change:
             ```bash
             {{ test_command }}
             ```
          4. Tests must stay green!

          If tests fail, revert and try again.

    rules:
      - name: keep_tests_green
        when: "tests_failing()"
        action: block
        message: "Tests are failing. Revert last change and try again."

    exit_conditions:
      - type: user_approval
        prompt: "Refactoring complete. Ready to finalize?"

    transitions:
      - to: complete
        when: approved

  - name: complete
    description: TDD cycle complete
    allowed_tools: all

    on_enter:
      - action: inject_context
        template: |
          ## TDD Cycle Complete

          The feature has been implemented following TDD:
          - Requirements understood
          - Tests written first
          - Minimal implementation
          - Code refactored

          Final verification:
          ```bash
          {{ test_command }}
          ```

triggers:
  on_session_start:
    - action: enter_step
      step: understand
