# Agent Delegation Workflow
# This workflow demonstrates delegating subtasks to subagents while the parent
# coordinates and reviews results.
#
# Usage: Copy to ~/.gobby/workflows/ or .gobby/workflows/
# Activate: Set workflow_name when spawning agent, or use gobby workflows set

name: agent-delegation
description: Delegate subtasks to subagents with parent coordination
version: "1.0"
type: step

# Initial variables set when workflow activates
variables:
  max_parallel_agents: 3
  agent_timeout: 300
  require_review: true

steps:
  - name: plan
    description: Plan the work and identify delegatable subtasks
    allowed_tools:
      - Read
      - Glob
      - Grep
      - WebSearch
      - WebFetch
      - TodoWrite
      - AskUserQuestion
    blocked_tools:
      - Edit
      - Write
      - Bash

    on_enter:
      - action: inject_context
        template: |
          ## Delegation Planning
          You are in the planning phase. Your goal is to:
          1. Understand the task requirements
          2. Break down into subtasks suitable for delegation
          3. Identify which subtasks can run in parallel

          DO NOT edit files in this phase. Focus on research and planning.

    exit_conditions:
      - type: user_approval
        prompt: "Plan complete. Ready to spawn agents for subtasks?"

    transitions:
      - to: delegate
        when: approved

  - name: delegate
    description: Spawn agents for each subtask
    allowed_tools:
      - Read
      - Glob
      - Grep
      - mcp__gobby__call_tool  # For gobby-agents tools
      - TodoWrite
    blocked_tools:
      - Edit
      - Write
      - Bash

    on_enter:
      - action: inject_context
        template: |
          ## Agent Delegation
          Spawn agents for each subtask using gobby-agents tools:

          ```python
          # Start a subagent
          call_tool(server_name="gobby-agents", tool_name="spawn_agent", arguments={
              "prompt": "Implement feature X...",
              "mode": "in_process",  # or "terminal" for parallel
              "parent_session_id": current_session_id,
              "timeout": {{ agent_timeout }},
          })
          ```

          You can spawn up to {{ max_parallel_agents }} agents in parallel.

    rules:
      - name: limit_parallel_agents
        when: "count_running_agents() >= max_parallel_agents"
        action: block
        message: "Maximum {{ max_parallel_agents }} parallel agents allowed"

    transitions:
      - to: review
        when: all_agents_complete

  - name: review
    description: Review agent results and integrate
    allowed_tools: all
    blocked_tools:
      # Block only agent-spawning tools; allow gobby-tasks/worktrees/memory
      - gobby-agents:spawn_agent
      - gobby-agents:stop_agent

    on_enter:
      - action: inject_context
        template: |
          ## Review Phase
          All agents have completed. Review their results:

          {% if require_review %}
          1. Check each agent's output for correctness
          2. Verify integration between components
          3. Run tests if applicable
          {% endif %}

          You may now edit files to make final adjustments.

    exit_conditions:
      - type: user_approval
        prompt: "Integration complete. Ready to finalize?"

    transitions:
      - to: complete
        when: approved

  - name: complete
    description: Final state - work complete
    allowed_tools: all

    on_enter:
      - action: inject_context
        template: |
          ## Workflow Complete
          The agent delegation workflow has completed successfully.
          All subtasks have been delegated, reviewed, and integrated.

triggers:
  on_session_start:
    - action: enter_step
      step: plan
