name: memory-aware-dev
description: "Development workflow with memory-driven context awareness"
version: "1.0"

# This workflow demonstrates advanced memory patterns:
# - Automatic context injection at start
# - Memory sync on pause/resume
# - Phase-specific memory retrieval

settings:
  memory_min_importance: 0.3
  reflect_after_actions: 15

phases:
  - name: understand
    description: "Understand the codebase with memory assistance"

    on_enter:
      - action: memory_inject
        min_importance: 0.3
        description: "Load project context from memories"

      - action: inject_message
        content: |
          You are in UNDERSTAND mode. Review the project memories above.

          Use Read, Glob, and Grep to explore the codebase.
          When you discover important patterns or facts, note them
          for later storage in memory.

    allowed_tools:
      - Read
      - Glob
      - Grep
      - WebSearch
      - WebFetch
      - AskUserQuestion

    blocked_tools:
      - Edit
      - Write
      - Bash

    exit_conditions:
      - approval: "Understanding complete. Ready to implement?"

  - name: implement
    description: "Implement with awareness of project patterns"

    on_enter:
      - action: switch_mode
        mode: implement
      - action: inject_message
        content: |
          You are now in IMPLEMENT mode.

          Remember to follow the project patterns from the injected memories.
          When done, suggest any new patterns worth remembering.

    allowed_tools: all

    transitions:
      - to: reflect
        when: "phase_action_count >= 15"
      - to: reflect
        when: "tool_result.is_error"

  - name: reflect
    description: "Review progress and capture learnings"

    on_enter:
      - action: inject_message
        content: |
          REFLECTION CHECKPOINT

          Review what you've accomplished.

          Consider if you've discovered any patterns worth storing:
          - New project conventions?
          - User preferences observed?
          - Important architectural facts?

          Suggest using gobby-memory tools to store valuable learnings.

    allowed_tools:
      - Read
      - Glob
      - Grep
      - TodoWrite
      - AskUserQuestion

    blocked_tools:
      - Edit
      - Write
      - Bash

    transitions:
      - to: implement
        when: "user_says('continue') or user_says('proceed')"
      - to: understand
        when: "user_says('rethink') or user_says('explore')"

triggers:
  on_session_start:
    - action: memory_sync_import
    - action: enter_phase
      phase: understand
      when: "not workflow_state.phase"

  on_session_end:
    - action: memory_sync_export

# Memory storage examples for the implement phase:
#
# Store a discovered pattern:
#   call_tool(server_name="gobby-memory", tool_name="remember", arguments={
#       "content": "All API routes follow /api/v1/{resource} convention",
#       "memory_type": "pattern",
#       "importance": 0.7
#   })
#
# Store a user preference:
#   call_tool(server_name="gobby-memory", tool_name="remember", arguments={
#       "content": "User prefers functional components over classes",
#       "memory_type": "preference",
#       "importance": 0.8
#   })
