# Parallel Worktree Agents Workflow
# This workflow demonstrates spawning multiple agents in isolated git worktrees
# for parallel development of independent features.
#
# Usage: Copy to ~/.gobby/workflows/ or .gobby/workflows/
# Activate: Set workflow_name when spawning agent, or use gobby workflows set

name: parallel-worktree-agents
description: Spawn agents in isolated worktrees for parallel development
version: "1.0"
type: step

variables:
  base_branch: main
  max_worktrees: 5
  cleanup_on_merge: true

steps:
  - name: analyze
    description: Analyze task and identify parallelizable features
    allowed_tools:
      - Read
      - Glob
      - Grep
      - WebSearch
      - TodoWrite
      - AskUserQuestion
    blocked_tools:
      - Edit
      - Write
      - Bash

    on_enter:
      - action: inject_context
        template: |
          ## Parallel Work Analysis
          Analyze the requirements and identify features that can be developed in parallel.

          Each parallel feature will get:
          - Its own git worktree (isolated directory)
          - Its own branch
          - Its own agent session

          Consider:
          - Which features are independent?
          - What's the dependency order?
          - How many can run simultaneously?

    exit_conditions:
      - type: user_approval
        prompt: "Ready to create worktrees and spawn agents?"

    transitions:
      - to: spawn_worktrees
        when: approved

  - name: spawn_worktrees
    description: Create worktrees and spawn agents
    allowed_tools:
      - Read
      - Glob
      - mcp__gobby__call_tool  # For gobby-worktrees and gobby-agents
      - TodoWrite
    blocked_tools:
      - Edit
      - Write
      - Bash

    on_enter:
      - action: inject_context
        template: |
          ## Creating Worktrees and Spawning Agents

          Use gobby-worktrees to create isolated development environments:

          ```python
          # Option 1: Create worktree and spawn agent in one call
          call_tool(server_name="gobby-worktrees", tool_name="spawn_agent_in_worktree", arguments={
              "prompt": "Implement feature X with full tests",
              "branch_name": "feature/feature-x",
              "base_branch": "{{ base_branch }}",
              "task_id": "gt-xxx",  # Link to task for tracking
              "parent_session_id": current_session_id,
              "mode": "terminal",  # Run in separate terminal
              "terminal": "auto",
          })

          # Option 2: Create worktree first, then spawn agent
          result = call_tool(server_name="gobby-worktrees", tool_name="create_worktree", arguments={
              "branch_name": "feature/feature-y",
              "base_branch": "{{ base_branch }}",
              "task_id": "gt-yyy",
          })

          call_tool(server_name="gobby-agents", tool_name="start_agent", arguments={
              "prompt": "Implement feature Y",
              "worktree_id": result["worktree_id"],
              "mode": "terminal",
              "parent_session_id": current_session_id,
          })
          ```

          Maximum {{ max_worktrees }} worktrees allowed simultaneously.

    rules:
      - name: limit_worktrees
        when: "active_worktrees_count() > max_worktrees"
        action: block
        message: "Maximum {{ max_worktrees }} active worktrees allowed"

    transitions:
      - to: monitor
        when: agents_spawned

  - name: monitor
    description: Monitor agent progress and handle completion
    allowed_tools:
      - Read
      - Glob
      - Grep
      - mcp__gobby__call_tool
      - TodoWrite
    blocked_tools:
      - Edit
      - Write

    on_enter:
      - action: inject_context
        template: |
          ## Monitoring Parallel Agents

          Monitor agent progress:
          ```python
          # List running agents
          call_tool(server_name="gobby-agents", tool_name="list_agents", arguments={
              "parent_session_id": current_session_id,
          })

          # Get result of completed agent
          call_tool(server_name="gobby-agents", tool_name="get_agent_result", arguments={
              "run_id": "run-xxx",
          })

          # List worktrees
          call_tool(server_name="gobby-worktrees", tool_name="list_worktrees", arguments={
              "status": "active",
          })
          ```

          When an agent completes, sync its worktree and prepare for merge.

    transitions:
      - to: integrate
        when: all_agents_complete

  - name: integrate
    description: Merge completed branches and cleanup
    allowed_tools: all

    on_enter:
      - action: inject_context
        template: |
          ## Integration Phase

          All agents have completed. Now:

          1. Review each worktree's changes
          2. Sync worktrees with {{ base_branch }}:
             ```python
             call_tool(server_name="gobby-worktrees", tool_name="sync_worktree", arguments={
                 "worktree_id": "wt-xxx",
                 "strategy": "merge",
             })
             ```
          3. Resolve any conflicts
          4. Merge branches to {{ base_branch }}
          5. Mark worktrees as merged:
             ```python
             call_tool(server_name="gobby-worktrees", tool_name="mark_worktree_merged", arguments={
                 "worktree_id": "wt-xxx",
             })
             ```
          {% if cleanup_on_merge %}
          6. Cleanup merged worktrees:
             ```python
             call_tool(server_name="gobby-worktrees", tool_name="delete_worktree", arguments={
                 "worktree_id": "wt-xxx",
             })
             ```
          {% endif %}

    exit_conditions:
      - type: user_approval
        prompt: "All branches merged and cleaned up?"

    transitions:
      - to: complete
        when: approved

  - name: complete
    description: Workflow complete
    allowed_tools: all

    on_enter:
      - action: inject_context
        template: |
          ## Parallel Development Complete

          All features have been developed in parallel and merged.

          Summary:
          - Worktrees created and cleaned up
          - All branches merged to {{ base_branch }}
          - Ready for final testing

triggers:
  on_session_start:
    - action: enter_step
      step: analyze
