name: test-driven
description: "Test-Driven Development: Red -> Green -> Refactor"
type: step
version: "1.0"

steps:
  - name: red
    description: "Write a failing test first"

    on_enter:
      - action: inject_message
        content: |
          RED PHASE - Write a Failing Test

          Write a test for the next piece of functionality.
          The test MUST fail initially (no implementation yet).

          Guidelines:
          - One test at a time
          - Test should be specific and focused
          - Run the test to confirm it fails

          Say "test written" or "green" when ready to implement.

    allowed_tools:
      - Read
      - Glob
      - Grep
      - Write
      - Edit
      - Bash
      - TodoWrite

    transitions:
      - to: green
        when: "user_says('green') or user_says('test written') or user_says('implement')"

  - name: green
    description: "Write minimal code to pass the test"

    on_enter:
      - action: inject_message
        content: |
          GREEN PHASE - Make the Test Pass

          Write the MINIMAL code needed to make the test pass.
          - Don't over-engineer
          - Don't add features not required by the test
          - Focus on making it work, not making it perfect

          Run tests frequently. Say "passing" or "refactor" when tests pass.

    allowed_tools: all

    transitions:
      - to: refactor
        when: "user_says('refactor') or user_says('passing') or user_says('tests pass')"
      - to: red
        when: "user_says('red') or user_says('more tests')"

  - name: refactor
    description: "Improve code while keeping tests green"

    on_enter:
      - action: inject_message
        content: |
          REFACTOR PHASE - Improve the Code

          Clean up the implementation while keeping tests passing.
          - Remove duplication
          - Improve naming
          - Simplify logic
          - Extract methods/functions if needed

          Run tests after each change. Options:
          - "red" - Write another test
          - "done" - Complete the TDD cycle

    allowed_tools: all

    transitions:
      - to: red
        when: "user_says('red') or user_says('next test') or user_says('another test')"
      - to: complete
        when: "user_says('done') or user_says('complete') or user_says('finished')"

  - name: complete
    description: "TDD cycle complete"

    on_enter:
      - action: inject_message
        content: |
          TDD CYCLE COMPLETE

          All tests written and passing. Code is clean and refactored.

          To start another TDD cycle, activate this workflow again.

triggers:
  on_session_start:
    - action: load_workflow_state
    - action: enter_step
      step: red
      when: "not workflow_state.step"

  on_session_end:
    - action: save_workflow_state
