name: session-lifecycle
description: "Unified session lifecycle: context handoff and memory"
type: lifecycle

settings:
  priority: 10 # Run first - critical for handoff before other LLM calls

# Session-scoped variables (can be overridden per session)
# These provide runtime control over behavior settings
variables:
  # Task enforcement - require active task before file modifications
  require_task_before_edit: true
  # Auto-decompose multi-step task descriptions into subtasks
  auto_decompose: true
  # Enable TDD mode for task expansion (test-implementation pairs)
  tdd_mode: true

  # Validation delegation - use a faster/cheaper model for linting and tests
  # Set to null to disable delegation (run inline)
  validation_model: "haiku"
  validation_timeout: 1800 # 30 minutes for full test suite

triggers:
  on_stop:
    # Commit enforcement - block stop if task has uncommitted changes
    # Skip in plan mode (set via gobby-workflows.set_variable when entering plan mode)
    - action: require_commit_before_stop
      when: "not variables.get('plan_mode')"

  on_session_start:
    # Capture baseline dirty files for session-aware commit detection
    # Must run FIRST so baseline is captured before any modifications
    - action: capture_baseline_dirty_files

    # Context handoff - inject previous session summary
    - action: inject_context
      when: "event.data.get('source') == 'clear'"
      source: previous_session_summary
      require: true # Block if handoff context missing
      template: |
        ## Previous Session Context
        *Injected by Gobby session handoff*

        {{ summary }}

    # Context handoff - inject compact handoff after compaction
    - action: inject_context
      when: "event.data.get('source') == 'compact'"
      source: compact_handoff
      require: true # Block if handoff context missing
      template: |
        ## Continuation Context
        *Injected by Gobby compact handoff*

        {{ handoff }}

    # Memory sync - import from JSONL for Git persistence
    - action: memory_sync_import

    # Validation delegation notice - direct ruff/mypy/pytest commands will be blocked
    - action: inject_message
      when: "variables.get('validation_model')"
      content: |
        ## Validation Delegation

        Direct `ruff`, `mypy`, and `pytest` commands are blocked. Delegate to {{ variables.validation_model }} via `gobby-agents.start_agent(mode="headless")`. The hook will provide the exact command when blocked.

  on_before_agent:
    # Memory recall - inject memories relevant to the user's prompt via semantic search
    - action: memory_recall_relevant
      limit: 5
      min_importance: 0.7

  on_before_tool:
    # Validation delegation - block direct ruff/mypy/pytest and require delegation
    - action: require_validation_delegation

    # Task enforcement - require active task before file modifications
    # Skip in plan mode (planning only writes to plan files)
    - action: require_active_task
      when: "not variables.get('plan_mode')"

  on_session_end:
    # Session summary generation
    - action: generate_handoff
      when: "event.data.get('reason') == 'clear'"
      include:
        - artifacts
        - pending_tasks
      template: |
        Analyze this Claude Code session transcript and create a comprehensive session summary.

        ## Transcript (last 50 turns):
        {transcript_summary}

        ## Last Messages:
        {last_messages}

        ## Git Status:
        {git_status}

        ## Files Changed:
        {file_changes}

        Create a markdown summary with the following sections (do NOT include a top-level '# Session Summary' header):

        ## Overview
        [1-2 paragraph summary of what was accomplished in this session]

        ## Key Decisions
        [List of important technical or architectural decisions made, with bullet points]

        ## Important Lessons Learned
        [Technical insights, gotchas, or patterns discovered, with bullet points]

        ## Substantive Interrupts
        [Times when the user changed direction significantly - NOT simple "continue" or "resume" prompts]

        ## Research & Epiphanies
        [Key discoveries from research or debugging that should be remembered, with bullet points]

        ### Interactions (X substantive of Y total)
        [This section will be automatically populated with substantive interactions from the session]

        ## Files Changed
        {file_changes}
        [Add specific details about WHY each file was changed and WHAT the changes accomplish.]

        ## Git Status
        ```
        {git_status}
        ```

        ## Claude Specific Todo List (or equivalent if provided by another LLM)
        [This section will be automatically populated with the actual TodoWrite list if it exists]

        ## Next Steps
        [Concrete, numbered suggestions for what to do when resuming work. Be specific and actionable.]

        Focus on actionable insights and context that would be valuable when resuming work later.
        Use only ASCII-safe characters - avoid Unicode em-dashes, smart quotes, or special characters.

    # Memory extraction - extract learnings to memory
    - action: memory_extract

    # Memory sync - export to JSONL for Git persistence
    - action: memory_sync_export

  on_pre_compact:
    # Extract structured context before compaction
    # Saves formatted markdown to session.compact_markdown
    - action: extract_handoff_context

    # Generate LLM summary with cumulative compression
    # Each compact builds on previous summary, weighting recent work higher
    - action: generate_handoff
      mode: compact
      template: |
        You are creating a session continuation summary after a compaction event.

        ## Context from Earlier in This Session (if any):
        {previous_summary}

        If there is previous context above, focus your summary on what happened AFTER
        that point. Compress the historical context into a brief "Session History" section.
        If no previous context, this is the first segment - summarize the full session.

        ## Current Transcript:
        {transcript_summary}

        ## Last Messages:
        {last_messages}

        ## Git Status:
        {git_status}

        ## Files Changed:
        {file_changes}

        ---

        Create a continuation summary optimized for resuming work after compaction.
        Use these sections:

        ### Current Focus
        [What is being actively worked on RIGHT NOW - be specific and detailed.
        This is the most important section.]

        ### This Segment's Progress
        [Bullet points of what was accomplished in this segment]

        ### Session History
        [1-2 sentences summarizing the overall session journey. Include if there was
        previous context, otherwise skip this section.]

        ### Technical State
        - Key files modified: [list files]
        - Git status: [uncommitted changes summary]
        - Any blockers or pending items

        ### Next Steps
        [Numbered list of concrete actions to take when resuming]

        IMPORTANT: Prioritize recency. "Current Focus" and "This Segment's Progress"
        should be detailed and specific. Historical context should be compressed.
        Use only ASCII-safe characters.
